
package br.edu.ifpb.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraSOAP", targetNamespace = "http://soap.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraSOAP {


    /**
     * 
     * @param c
     * @param d
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resposta", targetNamespace = "")
    @RequestWrapper(localName = "somar", targetNamespace = "http://soap.ifpb.edu.br/", className = "br.edu.ifpb.soap.Somar")
    @ResponseWrapper(localName = "somarResponse", targetNamespace = "http://soap.ifpb.edu.br/", className = "br.edu.ifpb.soap.SomarResponse")
    @Action(input = "http://soap.ifpb.edu.br/CalculadoraSOAP/somarRequest", output = "http://soap.ifpb.edu.br/CalculadoraSOAP/somarResponse")
    public int somar(
        @WebParam(name = "c", targetNamespace = "")
        int c,
        @WebParam(name = "d", targetNamespace = "")
        int d);

}
